FROM oven/bun:1

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./apps/http_server ./apps/http_server

RUN bun install
RUN bun run db:generate

EXPOSE 3003

CMD [ "bun" , "run" , "start:backend" ]

